<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.clojars.cartesiantheatrics</groupId>
    <artifactId>manifold3d</artifactId>
    <version>1.0.39</version>
    <packaging>jar</packaging>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
            <comments>A business-friendly OSS license</comments>
        </license>
    </licenses>

    <properties>
        <manifold.build.dir>${project.basedir}/../../build</manifold.build.dir>
        <manifold.library.name>libmanifold.so</manifold.library.name>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>1.5.9</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <distributionManagement>
        <repository>
            <id>clojars</id>
            <name>Clojars repository</name>
            <url>https://clojars.org/repo</url>
        </repository>
    </distributionManagement>

    <profiles>
        <profile>
            <id>macos-native</id>
            <activation><os><family>mac</family></os></activation>
            <properties><manifold.library.name>libmanifold.dylib</manifold.library.name></properties>
        </profile>
    </profiles>

    <build>
        <resources>
            <resource>
                <directory>${manifold.build.dir}/bin</directory>
            </resource>
            <resource>
                <directory>${manifold.build.dir}/src/</directory>
                <includes>
                    <include>libmanifold.so</include>
                    <include>libmanifold.dylib</include>
                </includes>
            </resource>
            <resource>
                <directory>${manifold.build.dir}/src/manifold/Release</directory>
                <includes>
                    <include>manifold.dll</include>
                </includes>
            </resource>
        </resources>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>stage-native-library</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <delete file="${project.build.outputDirectory}/${manifold.library.name}"/>
                                <copy file="${manifold.build.dir}/src/${manifold.library.name}"
                                      tofile="${project.build.outputDirectory}/${manifold.library.name}"/>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.bytedeco</groupId>
                <artifactId>javacpp</artifactId>
                <version>1.5.9</version>
                <configuration>
                    <classPath>${project.build.outputDirectory}</classPath>
                    <linkPath>${manifold.build.dir}/src/</linkPath>
                    <includePaths>
                        <includePath>${project.build.sourceDirectory}</includePath>
                        <includePath>${project.basedir}/src/main/cpp/manifold3d/</includePath>
                        <includePath>${project.basedir}/../../include/</includePath>
                        <includePath>${project.basedir}/../../src/third_party/clipper2/CPP/Clipper2Lib/include/</includePath>
                        <includePath>${manifold.build.dir}/_deps/texttopolygon-src/include</includePath>
                        <includePath>${manifold.build.dir}/_deps/freetype2-src/include</includePath>
                        <includePath>${project.basedir}/../../src/</includePath>
                    </includePaths>
                    <preload>libmanifold.so</preload>
                    <copyLibs>false</copyLibs>

                </configuration>
                <executions>
                    <execution>
                        <id>process-classes</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                        <configuration>
                            <classOrPackageNames>
                                <classOrPackageName>manifold3d.*</classOrPackageName>
                                <classOrPackageName>manifold3d.manifold.*</classOrPackageName>
                                <classOrPackageName>manifold3d.pub.*</classOrPackageName>
                                <classOrPackageName>manifold3d.linalg.*</classOrPackageName>
                            </classOrPackageNames>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <classifier>${os.classifier}</classifier>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
